function(set_clang_as_c_compiler)
  find_program(CLANG_C_COMPILER "clang")
  if (CLANG_C_COMPILER)
    set(CMAKE_C_COMPILER ${CLANG_C_COMPILER} CACHE STRING "C Compiler" FORCE)
    message(STATUS "Find and use ${CMAKE_C_COMPILER}")
  else ()
    message(STATUS "Can't find clang, use default c compiler: ${CMAKE_C_COMPILER}")
  endif ()
endfunction()

function(set_clang_plusplus_as_cxx_compiler)
  find_program(CLANG_CXX_COMPILER "clang++")
  if (CLANG_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER ${CLANG_CXX_COMPILER} CACHE STRING "CXX Compiler" FORCE)
    message(STATUS "Find and use ${CMAKE_CXX_COMPILER}")
  else ()
    message(STATUS "Can't find clang++, use default c++ compiler: ${CMAKE_CXX_COMPILER}")
  endif ()
endfunction()
